services:
  postgres:
    image: postgres:17-bullseye
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: 'addressbook'
      POSTGRES_USER: 'addressbook'
      POSTGRES_DB: 'addressbook'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U addressbook
      interval: 2s
      timeout: 3s
      retries: 40

  jaeger:
    image: jaegertracing/all-in-one:1.63.0
    ports:
      - '16686:16686'
      - '4318:4318'
      - '4317:4317'
    environment:
      - LOG_LEVEL=debug

volumes:
  postgres-data:
    name: postgres-data
